// site/src/components/antdv-token-previewer/component-demos/tag/info.tsx
import { Tag } from '@kaoniqiwa/trina-ui';
import type { ComponentDemo } from '../../interface';

const Demo = () => <Tag color="processing">Info</Tag>;

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorInfo', 'colorInfoBg', 'colorInfoBorder'],
  key: 'info',
};

export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/message/info.tsx
import { defineComponent } from 'vue';
import { message, Button } from '@kaoniqiwa/trina-ui';
import type { ComponentDemo } from '../../interface';

const Demo = defineComponent({
  setup() {
    const info = () => {
      message.info('This is an info message');
    };

    return () => <Button onClick={info}>Info</Button>;
  },
});
const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorInfo'],
  key: 'info',
};

export default componentDemo;
