// site/src/components/antdv-token-previewer/component-demos/tag/info.tsx
import { Tag } from '@kaoniqiwa/trina-ui';
import type { ComponentDemo } from '../../interface';

const Demo = () => <Tag color="processing">Info</Tag>;

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorInfo', 'colorInfoBg', 'colorInfoBorder'],
  key: 'info',
};

export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/result/info.tsx
import { defineComponent } from 'vue';
import { Result } from '@kaoniqiwa/trina-ui';

import type { ComponentDemo } from '../../interface';

const Demo = defineComponent({
  setup() {
    return () => <Result status={'info'} title="Demo示意" subTitle="status 为info" />;
  },
});

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorInfo'],
  key: 'info',
};

export default componentDemo;
