// site/src/components/antdv-token-previewer/component-demos/checkbox/disabled.tsx
import { Checkbox } from '@kaoniqiwa/trina-ui';
import type { ComponentDemo } from '../../interface';

const Demo = () => <Checkbox disabled>Checkbox</Checkbox>;

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorTextDisabled', 'colorBgContainerDisabled'],
  key: 'disabled',
};

export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/datePicker/disabled.tsx
import { defineComponent } from 'vue';
import { DatePicker, Space } from '@kaoniqiwa/trina-ui';
import type { ComponentDemo } from '../../interface';

const Demo = defineComponent({
  setup() {
    return () => (
      <Space direction="vertical">
        <DatePicker disabled />
        <DatePicker disabled picker="week" />
        <DatePicker disabled picker="month" />
        <DatePicker disabled picker="quarter" />
        <DatePicker disabled picker="year" />
      </Space>
    );
  },
});

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorBgContainerDisabled', 'colorTextDisabled'],
  key: 'disabled',
};

export default componentDemo;
